/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ILucideChevronDown: typeof import('~icons/lucide/chevron-down')['default']
    ILucideChevronUp: typeof import('~icons/lucide/chevron-up')['default']
    ILucideTrash2: typeof import('~icons/lucide/trash2')['default']
    TaskInput: typeof import('./src/components/TaskInput.vue')['default']
  }
}
